In [1]:
import pandas as pd
fillers = pd.read_table('segment_fillers.tsv')

In [4]:
fillers[:5]

,defined_class,neuron,neur_name,neur_no,chordotonal_organ,chor_name,chor_no
0,NaN,FBbt:00047268,lch5-1,1,FBbt:00002832,a1,1
1,NaN,FBbt:00047268,lch5-1,1,FBbt:00002833,a2,2
2,NaN,FBbt:00047268,lch5-1,1,FBbt:00002834,a3,3
3,NaN,FBbt:00047268,lch5-1,1,FBbt:00002835,a4,4
4,NaN,FBbt:00047268,lch5-1,1,FBbt:00002836,a5,5

In [7]:
#change start to match value in protege (without FBbt:000)
#then advance protege value
start = 47273
defined_class = list()

for i in range(fillers.shape[0]):
    x = start + i
    ID = "FBbt:000"+str(x)
    defined_class.append(ID)

In [8]:
defined_class

['FBbt:00047273',
 'FBbt:00047274',
 'FBbt:00047275',
 'FBbt:00047276',
 'FBbt:00047277',
 'FBbt:00047278',
 'FBbt:00047279',
 'FBbt:00047280',
 'FBbt:00047281',
 'FBbt:00047282',
 'FBbt:00047283',
 'FBbt:00047284',
 'FBbt:00047285',
 'FBbt:00047286',
 'FBbt:00047287',
 'FBbt:00047288',
 'FBbt:00047289',
 'FBbt:00047290',
 'FBbt:00047291',
 'FBbt:00047292',
 'FBbt:00047293',
 'FBbt:00047294',
 'FBbt:00047295',
 'FBbt:00047296',
 'FBbt:00047297',
 'FBbt:00047298',
 'FBbt:00047299',
 'FBbt:00047300',
 'FBbt:00047301',
 'FBbt:00047302',
 'FBbt:00047303',
 'FBbt:00047304',
 'FBbt:00047305',
 'FBbt:00047306',
 'FBbt:00047307']

In [9]:
fillers.defined_class = defined_class

In [10]:
fillers

,defined_class,neuron,neur_name,neur_no,chordotonal_organ,chor_name,chor_no
0,FBbt:00047273,FBbt:00047268,lch5-1,1,FBbt:00002832,a1,1
1,FBbt:00047274,FBbt:00047268,lch5-1,1,FBbt:00002833,a2,2
2,FBbt:00047275,FBbt:00047268,lch5-1,1,FBbt:00002834,a3,3
3,FBbt:00047276,FBbt:00047268,lch5-1,1,FBbt:00002835,a4,4
4,FBbt:00047277,FBbt:00047268,lch5-1,1,FBbt:00002836,a5,5
5,FBbt:00047278,FBbt:00047268,lch5-1,1,FBbt:00002837,a6,6
6,FBbt:00047279,FBbt:00047268,lch5-1,1,FBbt:00002838,a7,7
7,FBbt:00047280,FBbt:00047271,lch5-2,2,FBbt:00002832,a1,1
8,FBbt:00047281,FBbt:00047271,lch5-2,2,FBbt:00002833,a2,2
9,FBbt:00047282,FBbt:00047271,lch5-2,2,FBbt:00002834,a3,3
10,FBbt:00047283,FBbt:00047271,lch5-2,2,FBbt:00002835,a4,4
11,FBbt:00047284,FBbt:00047271,lch5-2,2,FBbt:00002836,a5,5
12,FBbt:00047285,FBbt:00047271,lch5-2,2,FBbt:00002837,a6,6
13,FBbt:00047286,FBbt:00047271,lch5-2,2,FBbt:00002838,a7,7
14,FBbt:00047287,FBbt:00047269,lch5-3,3,FBbt:00002832,a1,1
15,FBbt:00047288,FBbt:00047269,lch5-3,3,FBbt:00002833,a2,2
16,FBbt:00047289,FBbt:00047269,lch5-3,3,FBbt:00002834,a3,3
17,FBbt:00047290,FBbt:00047269,lch5-3,3,FBbt:00002835,a4,4
18,FBbt:00047291,FBbt:00047269,lch5-3,3,FBbt:00002836,a5,5
19,FBbt:00047292,FBbt:00047269,lch5-3,3,FBbt:00002837,a6,6
20,FBbt:00047293,FBbt:00047269,lch5-3,3,FBbt:00002838,a7,7
21,FBbt:00047294,FBbt:00047272,lch5-4,4,FBbt:00002832,a1,1
22,FBbt:00047295,FBbt:00047272,lch5-4,4,FBbt:00002833,a2,2
23,FBbt:00047296,FBbt:00047272,lch5-4,4,FBbt:00002834,a3,3
24,FBbt:00047297,FBbt:00047272,lch5-4,4,FBbt:00002835,a4,4
25,FBbt:00047298,FBbt:00047272,lch5-4,4,FBbt:00002836,a5,5
26,FBbt:00047299,FBbt:00047272,lch5-4,4,FBbt:00002837,a6,6
27,FBbt:00047300,FBbt:00047272,lch5-4,4,FBbt:00002838,a7,7
28,FBbt:00047301,FBbt:00047270,lch5-5,5,FBbt:00002832,a1,1
29,FBbt:00047302,FBbt:00047270,lch5-5,5,FBbt:00002833,a2,2
30,FBbt:00047303,FBbt:00047270,lch5-5,5,FBbt:00002834,a3,3
31,FBbt:00047304,FBbt:00047270,lch5-5,5,FBbt:00002835,a4,4
32,FBbt:00047305,FBbt:00047270,lch5-5,5,FBbt:00002836,a5,5
33,FBbt:00047306,FBbt:00047270,lch5-5,5,FBbt:00002837,a6,6
34,FBbt:00047307,FBbt:00047270,lch5-5,5,FBbt:00002838,a7,7

In [11]:
fillers.to_csv('segment_fillers.tsv',sep='\t',index=False)